## NumPy Overview
- NumPy is a fundamental library for scientific computing in Python.
- NumPy's main feature is the ndarray (n-dimensional array) object, which allows efficient and fast array computations.

1. Creating Arrays
2. Shaping and Transposition
3. Mathematical Operations
4. Indexing and Slicing

In [ ]:
!pip install numpy

In [1]:
import numpy as np

### 1. Creating Numpy Arrays

In [ ]:
# 1.1 Using Lists
arr1 = [1, 2, 3, 4, 5]
arr1 = np.array(arr1)
print(arr1, type(arr1))
print(arr1.ndim, arr1.dtype, arr1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
1 int64 (5,)


In [ ]:
# 1.2 Using np.zeros and np.ones and Broadcasting
arr_of_0 = np.zeros((2,3))
arr_of_1 = np.ones((5,2))
print(arr_of_0)
print(arr_of_1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr_of_1 * 4.5 #Broadcasting

array([[4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5]])

In [ ]:
# 1.3 Using arange() method
np.arange(10, 30, 5) #generates numbers from [10, 30) with a gap of 5

array([10, 15, 20, 25])

In [ ]:
np.arange(0, 2, 0.3)  #generates numbers in the given range with a gap of 0.3

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
# 1.4 Using linspace() method
np.linspace(0, 2, 9)  #generates 9 equally spaced numbers from [0,2]

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# 1.5 Using concatenate() method
A = np.zeros((2,3))
B = np.ones((2,1))

In [ ]:
C = np.concatenate([A, B], axis=1)
print(C)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [ ]:
# Using random
print(np.random.random((4,3))) #Return random floats in the half-open interval [0.0, 1.0)

print(np.random.randint(50, 100, size=(2, 4))) #Generate a 2 x 4 array of ints between[50, 100]

[[0.28110092 0.27840426 0.72333969]
 [0.89486379 0.78264332 0.72292294]
 [0.3762566  0.03838626 0.24822121]
 [0.51218154 0.24876343 0.25911505]]
[[85 61 80 97]
 [92 78 86 50]]


### 2. Axes

In [ ]:
arr = np.random.randint(3,20, size=(3,2))
arr

array([[ 7, 14],
       [ 4, 15],
       [16,  8]])

In [ ]:
print(arr.sum()) # sum all entries

64


In [ ]:
print(arr.sum(axis=0))# sum over cols

[27 37]


In [ ]:
print(arr.sum(axis=1)) # sum over rows

[21 19 24]


In [ ]:
print(arr.sum(axis=1, keepdims=True))

[[21]
 [19]
 [24]]


### 3. Shaping the NumPy arrays
- Total number of elements cannot change.
- Use -1 to infer axis shape

In [6]:
a = np.array([1,2,3,4,5,6])

In [11]:
a.reshape(6,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [5]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = a.reshape(2,-1) # If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.ravel() # used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array
a

array([1, 2, 3, 4, 5, 6])

### 4. Transposition

In [ ]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a = a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [ ]:
a = np.transpose(a)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 5. Mathematical operators

In [ ]:
a = np.array([1, 2, 3],dtype = np.float32)
b = np.array([4, 5, 6],dtype = np.float32)

In [ ]:
# 5.1 Arithmetic operations are element-wise
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(b % a)

[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[0.25 0.4  0.5 ]
[0. 1. 0.]


In [13]:
# 5.2 Logical operator returns a bool array
arr = np.random.random((2,3))
print(arr)
arr > 0.5

[[0.72830719 0.50250383 0.44265376]
 [0.86142621 0.10666251 0.93080863]]


array([[ True,  True, False],
       [ True, False,  True]])

In [ ]:
# 5.3 In place operations modify the array
b /= a
b

array([4. , 2.5, 2. ], dtype=float32)

### 6. Universal functions
- Also called ufuncs
- Element-wise

In [20]:
a = np.array([0, 16, 'nan', 36, 60, 64, 90])

In [ ]:
np.sqrt(a)

array([0.        , 4.        , 5.47722558, 6.        , 7.74596669,
       8.        , 9.48683298])

In [ ]:
np.sin(a)

array([ 0.        , -0.28790332, -0.98803162, -0.99177885, -0.30481062,
        0.92002604,  0.89399666])

In [21]:
np.isnan(a)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.exp(a)

array([1.00000000e+00, 8.88611052e+06, 1.06864746e+13, 4.31123155e+15,
       1.14200739e+26, 6.23514908e+27, 1.22040329e+39])

### 7. Array Indexing and Slicing



In [ ]:
a = list(range(10))
print(a)
print(a[:3]) # indices 0, 1, 2
print(a[-3:]) # indices 7, 8, 9
print(a[3:8:2]) # indices 3, 5, 7
print(a[4:1:-1]) # indices 4, 3, 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2]
[7, 8, 9]
[3, 5, 7]
[4, 3, 2]


### 8. Stacking Arrays

In [25]:
# hstack() method
a = np.array([[3],
              [4]])
b = np.array([[1, 2],
              [6, 8]])
print(a.shape, b.shape)
np.hstack([a, b]) # No. of rows should be same

(2, 1) (2, 2)


array([[3, 1, 2],
       [4, 6, 8]])

In [ ]:
# vstack() method
a = np.array([[3, 5]])
b = np.array([[1, 2],
              [6, 8],
              [5, 4]])
print(a.shape, b.shape)
np.vstack([a, b]) # No. of cols should be same

(1, 2) (3, 2)


array([[3, 5],
       [1, 2],
       [6, 8],
       [5, 4]])

### 9. Questions

In [ ]:
a = np.array([-1, 4, 5])

In [ ]:
# 9.1 np.all() -> Test whether all array elements along a given axis evaluate to True.
print(np.all(a > 5))

False


In [ ]:
# 9.2 np.any() -> Test whether any array elements along a given axis evaluate to True.
print(np.any(a == 5))

True


### 10. Ordering

In [ ]:
a = np.random.randint(20, size=(3,3))
a

array([[ 3, 10,  5],
       [ 6, 16, 12],
       [12,  2,  1]])

In [ ]:
# 10.1 argmax() -> Returns the indices of the maximum values along an axis.
np.argmax(a, axis=0)

array([2, 1, 1])

In [ ]:
np.argmax(a, axis=1)

array([1, 1, 0])

In [ ]:
# 10.2 argmin() -> Returns the indices of the minimum values along an axis.
np.argmin(a, axis=0)

array([0, 2, 2])

In [ ]:
np.argmin(a, axis=1)

array([0, 0, 2])

### 11. Basic Statistics

In [ ]:
# 11.1 np.mean()
print(np.mean(a)) #overall mean
print(np.mean(a, axis = 0)) # column-wise mean
print(np.mean(a, axis = 1)) # row-wise mean

7.444444444444445
[7.         9.33333333 6.        ]
[ 6.         11.33333333  5.        ]


In [ ]:
# 11.2 np.std() -> standard deviation
print(np.std(a)) #overall standard deviation
print(np.std(a, axis = 0)) # column-wise standard deviation
print(np.std(a, axis = 1)) # row-wise standard deviation

4.94662873101157
[3.74165739 5.73488351 4.54606057]
[2.94392029 4.10960934 4.96655481]


In [ ]:
# 11.3 np.var() -> variance
print(np.var(a)) #overall variance
print(np.var(a, axis = 0)) # column-wise variance
print(np.var(a, axis = 1)) # row-wise variance

24.469135802469133
[14.         32.88888889 20.66666667]
[ 8.66666667 16.88888889 24.66666667]


### 12. Basic Linear Algebra


In [ ]:
# 12.1 np.cross() -> # Returns the cross product of two (arrays of) vectors. The cross product of a and b is a vector perpendicular to both a and b.
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [ ]:
# 12.2 np.dot() -> Dot product of two arrays
x = [1, 2, 3]
y = [4, 5, 6]
np.dot(x, y)

32

In [ ]:
# 12.3 np.outer() -> Outer product of two arrays.
a = np.array([1,2,3])
b = np.array([0,1,0])
print(a.shape, b.shape)
np.outer(a, b) # returns a 3x3 array

(3,) (3,)


array([[0, 1, 0],
       [0, 2, 0],
       [0, 3, 0]])

In [ ]:
# 12.4 np.inner() -> Inner product of two arrays.
a = np.array([1,2,3])
b = np.array([0,1,0])
print(a.shape, b.shape)
np.inner(a, b).shape #returns a scaler

(3,) (3,)


()

### 13. Saving and Loading Arrays

In [ ]:
# 13.1 Save an array to a binary file in NumPy .npy format.
x = np.arange(10)
print(x)
np.save("savedArr", x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 13.2 Load an array
np.load('savedArr.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])